### ISSUE TITLE
ETH contract generator

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-backend#12]
Implement ETH contract generator mirroring EOS functionality (price pushing etc.)

**Comment by zlumer** [comment]
To-do: add floats (same as price for now)

**Comment by zlumer** [comment]
18 decimal places
256 bit value

**Comment by Sindbag** [comment]
PR is open and requires code-review.

**Comment by Sindbag** [comment]
Is the task could be closed?

**Comment by zlumer** [comment]
Yes
