### ISSUE TITLE
ETH event reader

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-backend#3]
Data Update Event format is described here: DucaturFw/ducor-eth#1

- [x] load all requests from ETH blockchain events into application-level database
- [x] parse requests from blockchain-specific format to Universal Data Request format (`data hash`, `request id`, `receiver`, `blockchain`, `timestamp`)

**Comment by Sindbag** [comment]
Done by @alerdenisov

**Comment by Sindbag** [comment]
Found out, that some more checks and fixes needed:
 - [ ] fromBlock option to be filled properly
 - [ ] env variables requirement unification for pusher and watcher
 - [ ] Tests

**Comment by zlumer** [comment]
#50
