### ISSUE TITLE
ETH data pusher

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-backend#5]
- [x] push new data into contract based on Universal Data Request (as described in #2)
- [ ] raise DataPushed event on receiving contract

**Comment by Sindbag** [comment]
>  raise DataPushed event on receiving contract

Why? If we have mined transaction => data is pushed, isn't it?

**Comment by zlumer** [comment]
It's only for convenience. Won't affect anything else.

**Comment by Sindbag** [comment]
Problem here that it would require additional gas for nothing.

чт, 9 авг. 2018 г., 16:34 Dmitry Radkovskiy <notifications@github.com>:

**Comment by Sindbag** [comment]
As discussed, we do not monitor receiving contracts, so we have no need to emit events in constructor (suppose, if user needs it, he will emit it himself)
