### ISSUE TITLE
Return real tx hash and result from EOS pusher

### ISSUE THREAD

**Issue by zlumer** [DucaturFw/ducor-backend#8]
EOS `push()` should return real tx hash and result (it uses an always `true` placeholder now)

**Comment by zlumer** [comment]
See https://github.com/DucaturFw/ducor-backend/blob/c38cf3f5f6a7cd1bcfc2bc117103d8134b615a3c/src/blockchains/eos-push.ts#L79-L84

**Comment by alerdenisov** [comment]
Fixed with a78f84f53c04e6fdfae45d2e916392b3e19c6041
